config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

    match 'catalog/latest', :to => 'catalog#latest', via: [:get, :post]
  

  get 'catalog/index'

  get 'catalog/show'

  get 'catalog/search'

  get 'catalog/latest'

    namespace :admin do
        resources :books
       resources :author
        resources :publishers
    end
    
    scope :module => "admin" do
        resources :books
    end

    get 'about/index'
    
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"
    root :to => "sessions#new"
    resources :users
    resources :sessions  

   
    
    match ':controller(/:action(/:id(.:format)))', via: [:get, :post]
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= @page_title || 'Emporium' %></title>
<%= stylesheet_link_tag "application", media: "all",
"data-turbolinks-track" => true %>
<%= javascript_include_tag "application",
"data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
    
    
<script type = "text/javascript">
        
       
   window.onload = function() {

  function getScrollTop() {
    if (typeof window.pageYOffset !== 'undefined' ) {
      // Most browsers
      return window.pageYOffset;
    }

    var d = document.documentElement;
    if (d.clientHeight) {
      // IE in standards mode
      return d.scrollTop;
    }

    // IE in quirks mode
    return document.body.scrollTop;
  }

  window.onscroll = function() {
    var box = document.getElementById('shopping_cart'),
        scroll = getScrollTop();

    if (scroll <= 28) {
      box.style.top = "30px";
    }
    else {
      box.style.top = (scroll + 2) + "px";
    }
  };

};
    </script>    
    
</head>
<body>
<!--  -->
    <nav class="navbar navbar-inverse">
        
            <b><h1><div class="navbar-header">
      <a class="navbar-brand" href="#">EMPORIUM&trade; - Books on Rails</a>
                </div></h1></b><br/>
        
<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li><a href="#" >Logged in as <%= current_user.email %></a></li>
    <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log out'.html_safe, log_out_path %></li>
  <% else %>
    
        <li><%= link_to '<span class="glyphicon glyphicon-user"></span> Sign up'.html_safe, sign_up_path %></li> or
        <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> log in'.html_safe, log_in_path %></li>
    
  <% end %>
  <% if current_user %>
   </ul>     
        <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?('/admin/author') %>"><a href="/admin/author">Authors</a></li>
            <li class="<%= 'active' if current_page?('/admin/publishers') %>"><a href="/admin/publishers">Publishers</a></li>
            <li class="<%= 'active' if current_page?('/admin/books') %>"><a href="/admin/books">Books</a></li>
            <li class="<%= 'active' if current_page?('/catalog/index') %>"><a href="/catalog/index">Catalog</a></li>
            <li class="<%= 'active' if current_page?('/about') %>"><a href="/about">About</a></li>
      </ul>
    <% end %>
</nav>
    
    <div id="container" class="container-fluid">
        
        
         
        
<% if flash[:notice] %>
    <div id="notice" class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
        
        
        
        <div class="row">
            <div class="col-xs-12 col-md-8">
        
            
            <%= "<h1>#{@page_title}</h1>".html_safe if @page_title %>
        
   
    
    
    <%= yield %>
                
        
                
        
                
      
            
        </div>
        
        
        <div class="col-xs-6 col-md-4">
            
           <div id="shopping_cart">
            <% if @cart %>
               <%= render :partial => "cart/cart" %> </div>

            <%= drop_receiving_element("shopping_cart", :url => { :controller => "cart", :action => "add" }) %>
            <% end %>
           
        </div>
   
    
  
    
  

</div> 
        </div>
    
    <div class="navbar navbar-inverse navbar-fixed-bottom"><center><a href="/about">&copy; 2015 Emporium</a></center></div>
    
    
    
</body>
</html>